apiVersion: v1
kind: Service
metadata:
  name: urbit
  namespace: urbit
  annotations:
spec:
  clusterIP: 
  externalTrafficPolicy: Cluster
  selector:
    app: urbit
  ports:
    - name: https
      port: 80
      targetPort: 8080
    - name: http
      port: 38254
      targetPort: 38254
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.4.211
